version: "3.9"

services:
  db:
    image: postgres:15
    container_name: tarea_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: annara10
      POSTGRES_DB: tarea5
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tarea_app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://vw_user:annara10@db:5432/tarea5
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  db_data:
